library/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth.views import LogoutView



app_name = 'library'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    


    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='library:login'), name='logout'),
    path('register/', registerStudent.as_view(), name='register'),


    path('books/', BookView.as_view(), name='book-list'),
    path('book/create/', bookCreate.as_view(), name='book-create'),
    path('book/<slug:pk>/', BookDetail.as_view(), name= 'book'),
    path('book/<slug:id>/update/',bookCreate.as_view(), name='book-update'),
    path('book/<slug:id>/delete/', deleteBook.delete, name='book-delete'),
    path('book/charts', createChart.projectOnChart, name='show-chart'),


    path('students/', StudentView.as_view(), name='student-list'),
    path('student/create/', registerStudent.as_view(), name='student-create'),
    path('student/<slug:pk>/', StudentDetail.as_view(), name='student-detail'),
    path('student/<slug:id>/update/', registerStudent.as_view(), name='student-update'),
    path('student/<slug:id>/delete/', deleteStudent.delete, name='student-delete'),



    path('borrowers/', BorrowerView.as_view(), name='borrower-list'),
    path('borrower/create/', borrowBook.as_view(), name='borrower-create'),
    path('borrower/<slug:pk>/', BorrowerDetail.as_view(), name= 'borrower'),
    path('borrower/<slug:id>/update/', borrowBook.as_view(), name='borrower-update'),
    path('borrower/<slug:id>/delete/', borrowerDelete.delete, name='borrower-delete'),





]

library_management/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls')),
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate

from .models import Account, Book, Borrower


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Add a valid email address.')

    class Meta:
        model = Account
        fields = ('email', 'name', 'username','enrollment_no', 'password1', 'password2','pic' )


		
class BookForm(forms.ModelForm):
	class Meta:
		model=Book
		exclude = ('timesIssued',)

class IssueBook(forms.ModelForm):
	class Meta:
		model=Borrower
		fields='__all__'



class AccountAuthenticationForm(forms.ModelForm):

	password = forms.CharField(label='Password', widget=forms.PasswordInput)

	class Meta:
		model = Account
		fields = ('email', 'password')

	def clean(self):
		if self.is_valid():
			email = self.cleaned_data['email']
			password = self.cleaned_data['password']
			if not authenticate(email=email, password=password):
				raise forms.ValidationError("Invalid login")


class AccountUpdateForm(forms.ModelForm):

	class Meta:
		model = Account
		fields = ('name' ,'username', 'pic','is_active' )

        

	def clean_email(self):
		email = self.cleaned_data['email']
		try:
			account = Account.objects.exclude(pk=self.instance.pk).get(email=email)
		except Account.DoesNotExist:
			return email
		raise forms.ValidationError('Email "%s" is already in use.' % account)

	def clean_username(self):
		username = self.cleaned_data['username']
		try:
			account = Account.objects.exclude(pk=self.instance.pk).get(username=username)
		except Account.DoesNotExist:
			return username
		raise forms.ValidationError('Username "%s" is already in use.' % username)

library/views.py
from http.client import BAD_REQUEST
from urllib.request import Request
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView, DeleteView, UpdateView, FormView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.urls import reverse_lazy
from .forms import *
from django.http import request
from datetime import datetime, timedelta
from django.contrib import messages
from django.views import View
import logging
import boto3
import os
from botocore.exceptions import ClientError
from .snsContent import Publisher

a_publisher = Publisher()
class UserAccessMixin(PermissionRequiredMixin):
    def dispatch(self, request, *args, **kwargs):
        if not self.has_permission():
            return redirect('library:home')
        return super(UserAccessMixin, self).dispatch(request, *args, **kwargs)




class UserLoginView(LoginView):
    template_name='library/login.html'
    fields='__all__'
    redirect_authenticated_user=True

    def get_success_url(self):
        return reverse_lazy('library:home')
        
def registerUser(request):
    page = 'register'
    form = RegistrationForm()
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.is_active = True
            user.save()
            messages.success(request, 'Succefully Registered!')
            return redirect('library:home')
        else:
            messages.error(request, "An error occured while registering user!")

    context={
        'page':page,
        'form':form
    }
    return render(request, 'library/register.html', context)


class HomeView(LoginRequiredMixin, TemplateView):
    template_name='library/main.html'
    

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context['accounts']=Account.objects.all()
        context['books'] = Book.objects.all()
        search_input=self.request.GET.get('search-area') or ''
        if search_input:
            context['books']=context['books'].filter(
                title__startswith=search_input)

        context['search_input']=search_input
        return context


class BookView(LoginRequiredMixin, ListView):
    model=Book
    context_object_name='books'

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context['books']=context['books']

        search_input=self.request.GET.get('search-area') or ''
        if search_input:
            context['books']=context['books'].filter(
                title__startswith=search_input)

        context['search_input']=search_input

        return context

class BookDetail(LoginRequiredMixin, DetailView):
    model=Book
    context_object_name='book'
    template_name='library/book.html'


class StudentView(LoginRequiredMixin, UserAccessMixin, ListView):
    model=Account
    context_object_name='students'
    permission_required = 'students.view_students'
    template_name='library/student_list.html'

    def get_context_data(self,  *args,**kwargs):
        context=super().get_context_data(**kwargs)
        context['students']=Account.objects.all()
        context['students']=context['students'].exclude(is_admin=True)
        search_input=self.request.GET.get('search-area') or ''
        if search_input:
            context['students']=context['students'].filter(name__startswith=search_input)

        context['search_input']=search_input

        return context

class StudentDetail(LoginRequiredMixin, DetailView):
    model=Account
    context_object_name='student'
    template_name='library/student.html'


class BorrowerView(LoginRequiredMixin, ListView):
    model=Borrower
    context_object_name='borrowers'
    template_name = 'library/borrower_list.html'


    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        if self.request.user.is_admin or self.request.user.is_superuser:
            context['borrowers']=context['borrowers']
        else:
            context['borrowers']=context['borrowers'].filter(student = self.request.user.id)
        return context


class BorrowerDetail(LoginRequiredMixin,  DetailView):
    model=Borrower()
    context_object_name='borrower'
    template_name='library/borrower.html'


class registerStudent(View):
    def get(self,request,id="0"):
        if id=="0":
            form = RegistrationForm()
            context={
            'form':form
            }
            return render(request, 'library/register.html', context)
        else:
            student = Account.objects.get(pk=id)
            form = AccountUpdateForm(instance = student)
            context={
            'form':form
            }
            return render(request, 'library/student_update.html', context)

    def post(self, request, id="0"):
        if id=="0":
            form = RegistrationForm(request.POST, request.FILES)
        else:
            student = Account.objects.get(pk=id)
            form = AccountUpdateForm(request.POST,request.FILES,instance=student)  
        if form.is_valid():
            form.save()
            imgName = request.FILES['pic'].name;
            upload_file("lmsstudents",os.path.join("media/students", imgName))
            messages.success(request, 'Succefully Registered!')
            return redirect('library:student-list')
        else:
            messages.error(request, "An error occured while registering Student!")


class deleteStudent(LoginRequiredMixin):
    def delete(request, id="0"):
        student = Account.objects.get(pk = id)
        student.delete()
        return redirect('library:student-list')


class deleteBook(LoginRequiredMixin):
    def delete(request, id = "0"):
        book = Book.objects.get(pk = id)
        book.delete()
        return redirect('library:book-list')
        

class borrowerDelete(LoginRequiredMixin):
    def delete(requesr, id = "0"):
        borrower = Borrower.objects.get(pk = id)
        borrower.delete()
        return redirect('library:borrower-list')

# class bookCreate(LoginRequiredMixin, UserAccessMixin, CreateView):
#     model=Book
#     permission_required= 'books.add_books'
#     fields='__all__'
#     success_url=reverse_lazy('library:book-list')


#     def form_valid(self, form):
#         form.instance.user=self.request.user
#         return super(bookCreate, self).form_valid(form)
class bookCreate(LoginRequiredMixin,View):
    def get(self,request,id="0"):
        if id=="0":
            form = BookForm()
            context={
            'form':form
            }
            return render(request, 'library/book_form.html', context)
        else:
            book = Book.objects.get(pk=id)
            form = BookForm(instance = book)
            context={
            'form':form
            }
            return render(request, 'library/book_form.html', context)

    def post(self, request, id="0"):
        if id=="0":
            form = BookForm(request.POST,request.FILES)
            
        else:
            book = Book.objects.get(pk=id)
            form = BookForm(request.POST,request.FILES,instance=book)
            
        
        if form.is_valid():
            form.save()
            imgName = request.FILES['pic'].name;
            # upload_file("lmsbooks",imgName)
            upload_file("lmsbooks",os.path.join("media/books", imgName))
            messages.success(request, 'Succefully added a new book!')
            return redirect('library:book-list')
        else:
            messages.error(request, "An error occured while adding a book!")
    
def upload_file(bucket,file_name, object_key=None):
        """Upload a file to an S3 bucket
        :param file_name: File to upload
        :param bucket: Bucket to upload to
        :param key: S3 object key. If not specified then file_name is used
        :return: True if file was uploaded, else False
        """
        if object_key is None:
            object_key = file_name
        
        s3_client = boto3.client('s3')
        try:
            response = s3_client.upload_file(file_name, bucket, object_key)
            '''
            # an example of using the ExtraArgs optional parameter to set the ACL (access control list) value 'public-read' to the S3 object
            response = s3_client.upload_file(file_name, bucket, key, 
            ExtraArgs={'ACL': 'public-read'})
            '''
        except ClientError as e:
            logging.error(e)
            return False
        return True    
            
   


class borrowBook(LoginRequiredMixin,View):

    def get(self,request,id="0"):
        if id=="0":
            form = IssueBook()
            context={
            'form':form
            }
            return render(request, 'library/borrower_form.html', context)
        else:
            book = Borrower.objects.get(pk=id)
            form = IssueBook(instance = book)
            context={
            'form':form
            }
            return render(request, 'library/borrower_form.html', context)
        

    def post(self, request, id="0"):
        result="0";
        if id=="0":
            form = IssueBook(request.POST)
        else:
            book = Borrower.objects.get(pk=id)
            form = IssueBook(request.POST,instance=book)  
        if form.is_valid():
            instance = form.save(commit=False)
            book = Book.objects.get(id=instance.book.id)
            # string = "You have issued "+book

library/templates/library/base.html
<!doctype html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  <title>L.M.S</title>
</head>
<style>
  .card-img-top {
    width: 100%;
    height: 15vw;
    object-fit: cover;
  }

  .card {
    margin: 1em auto;
  }

  .about__img {
    margin-top: 1em;
    justify-self: center;
  }

  .profile {
    margin: auto;
    text-align: center;
    font-family: 'Gill Sans', 'Gill Sans MT', 'Calibri', 'Trebuchet MS', sans-serif;

  }

  .about__img img {
    width: 200px;
    border-radius: .5rem;
  }

  label {
    padding-top: 10px !important;
    display: block;
  }

  th,
  td {
    text-align: center;
    margin: auto;
  }

  .flex-container {
    overflow: auto;
  }
</style>

<body style="background-color: rgb(62, 64, 64);">

  <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
    <div class="container">
      <a class="navbar-brand" href="{% url 'library:home' %}">Library Management System</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'library:home' %}">Home</a>
          </li>




          {% if request.user.is_superuser or request.user.is_admin %}
          <li class="nav-item">
            <a class="nav-link " aria-current="page" href="{% url 'library:student-list' %}">Students List</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " aria-current="page" href="{% url 'library:student-create'%}">Add Student</a>
          </li>
          <!-- <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
              aria-expanded="false">
              Students
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{% url 'library:student-list' %}">Students List</a></li>
              <li><a class="dropdown-item" href="{% url 'library:student-create'%}">Add Student</a></li>

            </ul>
          </li> -->
          {% endif %}
          <li class="nav-item">
            <a class="nav-link " aria-current="page" href="{% url 'library:book-list' %}">Books List</a>
          </li>
          {% if request.user.is_superuser or request.user.is_admin %}
          <li class="nav-item">
            <a class="nav-link " aria-current="page" href="{% url 'library:book-create' %}">Add New Book</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " aria-current="page" href="{% url 'library:borrower-create' %}">Issue a Book</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " aria-current="page" href="{% url 'library:show-chart' %}">Show Charts</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link " aria-current="page" href="{% url 'library:borrower-list' %}">Books Issued</a>
          </li>
          <!-- <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
              aria-expanded="false">
              Books
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{% url 'library:book-list' %}">Books List</a></li>
              {% if request.user.is_superuser or request.user.is_admin %}
              <li><a class="dropdown-item" href="{% url 'library:book-create' %}">Add New Book</a></li>
              <li><a class="dropdown-item" href="{% url 'library:borrower-create' %}">Issue a Book</a></li>
              {% endif %}
              <li><a class="dropdown-item" href="{% url 'library:borrower-list' %}">Books Issued</a></li>
            </ul>
          </li> -->


          <li class="nav-item">
            <a class="nav-link " aria-current="page" href="{% url 'library:student-detail' request.user.id%}">View
              Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " aria-current="page" href="{%url 'library:logout'%}">Logout </a>         
          </li>

          <!-- <li><a class="dropdown-item" href="{% url 'library:student-detail' request.user.id%}">View Profile</a></li>
                  <li><a class="dropdown-item" href="{%url 'library:logout'%}">Logout</a></li> -->



          {% endif %}
        </ul>

      </div>
    </div>
  </nav>
  <div class="container" style="overflow: auto;">
    {% block content %} {% endblock content %}</div>


  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>


</body>

</html>

library/templates/library/book.html
{% extends 'library/base.html' %}
{% block content %}
<div class="profile">
{% if book.pic %}
<div class="about__img img">
    <img src="https://lmsbooks.s3.amazonaws.com{{book.pic.url}}" alt="">
</div>
{% else %}
<div class="about__img img">
    <img src="/static/avatar/open-book-clipart-03.png" alt="">
</div>
{% endif %}
{% if request.user.is_admin or request.user.is_superuser %}
<a  href="{% url 'library:book-update' book.id%}" class="btn btn-primary">Edit</a>
{% endif %}
<span><h1 style="color: white;">{{book.title|title}}</h1></span>
<p style="width: 50%; margin: auto; color: white;">{{book.summary}}</p>
<h4 style="margin: auto; color: white; margin-top: 10px;">Genre:</h4><p style="color: white;"> {{book.genre.all|join:', '}}</p>
 <h4 style="margin: auto; color: white;">ISBN:</h4> <p style="color: white;"> {{book.isbn}}</p>



</div>
{% endblock content %}

library/templates/library/book_form.html
{% extends 'library/base.html' %}
{% load crispy_forms_tags %}
{% block content %}


<div class="container" style="width:800px; margin:0 auto;margin-top: 20px;">
    <h1 style="color: white;">Add a new Book</h1>
</div>

<div class="card-body" style="width:800px; margin:0 auto; background-color: aliceblue; margin-top: 30px;">
    <a href="{% url 'library:book-list' %}" class="btn btn-primary">Back</a>
    <form method="POST" enctype="multipart/form-data"action="" autocomplete="off">
    {%csrf_token%}
    {{form.title|as_crispy_field}}   
    {{form.author|as_crispy_field}}   
    {{form.summary|as_crispy_field}}   
    {{form.isbn|as_crispy_field}}   
    {{form.genre|as_crispy_field}}   
    {{form.language|as_crispy_field}}   
    {{form.total_copies|as_crispy_field}}   
    {{form.available_copies|as_crispy_field}}   
    {{form.pic|as_crispy_field}}   
    <!-- <label >{{form.title.label}} </label>
    {{form.title}} 
    
    <label >{{form.author.label}} </label>
    {{form.author}} 
    <label >{{form.summary.label}} </label>
    {{form.summary}}
    
    <label >{{form.isbn.label}} </label>
    {{form.isbn}} 
    
    <label >{{form.genre.label}}</label>
    {{form.genre}} 
    
    <label >{{form.language.label}} </label> 
    {{form.language}}  
    
    <label >{{form.total_copies.label}}</label> 
    {{form.total_copies}}
    <label >{{form.available_copies.label}}</label> 
    {{form.available_copies}}
    <label >{{form.pic.label}}</label> 
    {{form.pic}} -->

    <label> <input class="button btn btn-primary" type="submit" value="Submit"></label>
    
    </form>
</div>



{% endblock content %}

library/templates/library/borrower.html
<h1>{{borrower}}</h1>

library/templates/library/borrower_confirm_delete.html
{% extends 'library/base.html' %}
{% block content %}

<div class="container" style="width:800px; margin:0 auto;margin-top: 40px; background-color: aliceblue;">
<div >
    <a href="{% url 'library:borrower-list' %}" class="btn btn-primary" style="margin-top: 20px;">Back</a>
</div>

<div style="margin-top: 50px;">
    <form method = "POSt">
        {%csrf_token%}
        <b style="color: black;">Are you sure you want to delete the book issued by'{{borrower|title}}'?</b><br>
        <input class="button btn btn-danger" type="submit" value="Yes, Delete" style="margin-top: 30px; margin-bottom: 20px;">
        </form>
</div>
</div>


{% endblock content %}

library/templates/library/borrower_form.html
{% extends 'library/base.html' %}
{% load crispy_forms_tags %}
{% block content %}



<div class="container" style="width:800px; margin:0 auto;margin-top: 20px;">
    <h1 style="color: white;">Issue Book</h1>
</div>
<div class="card-body" style="width:800px; margin:0 auto; background-color: aliceblue; margin-top: 50px;">

    <a href="{% url 'library:borrower-list' %}" class="btn btn-primary">Back</a>
    <form method="POST" action="" autocomplete="off">
    {%csrf_token%}
    {{form.student|as_crispy_field}} 
    {{form.book|as_crispy_field}} 
    {{form.issue_date|as_crispy_field}} 
    {{form.return_date|as_crispy_field}} 
    <!-- <label >{{form.student.label}} </label>
    {{form.student}} 
    
    <label >{{form.book.label}} </label>
    {{form.book}} 
    <label >{{form.issue_date.label}} </label>
    {{form.issue_date}}
    
    <label >{{form.return_date.label}} </label>
    {{form.return_date}}  -->
    

    <label> <input class="button btn btn-primary"  type="submit" value="Submit"></label>



    </form>
</div>


{% endblock content %}

library/templates/library/borrower_list.html
{% extends "library/base.html" %} {% block content %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong>{{message}}</strong> 
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}
<div class="container">
  <div class="row" style="margin: auto; margin-top: 40px;">
    <form method="GET" class="d-flex">
      <input class="form-control me-2" type="text" placeholder="Search" name="search-area" aria-label="Search" style="background-color:white ;"
        value="{{search_input}}">
      <button class="btn btn-info" type="submit">Search</button>
    </form>
  </div>
  <h1 style="margin-top: 10px; color: white; margin-top: 50px;">Here are the list of books which are borrowed.</h1>
<table class="table table-striped table-dark" style="margin: auto;margin-top: 40px;">
  <thead>
    <tr>
      <th scope="col">SN</th>
      <th scope="col">Student Name</th>
      <th scope="col">Book</th>
      <th scope="col">Return Date</th>
      <th scope="col">Fine</th>
      {% if request.user.is_admin or request.user.is_superuser %}
      <th scope="col">Action</th>{% endif %}
    </tr>
  </thead>
  {% if borrowers %}
  <tbody>
    {% for borrower in borrowers %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{borrower.student.name}}</td>
      <td>{{borrower.book.title}}</td>
      <td>{{borrower.return_date}}</td>
      <td>{{borrower.fine}}</td>
      <td>{% if request.user.is_admin or request.user.is_superuser %}
        <a href="{% url 'library:borrower-update' borrower.id%}" class="btn btn-primary">Update</a>  <a href="{% url 'library:borrower-delete' borrower.id%}" class="btn btn-danger">Delete</a>
        {% endif %}</td>
    </tr>

    {% endfor %}
  </tbody>
  {% else %}
  <tbody><tr><td colspan="6"> No Books Issued.</td></tr></tbody>
  {% endif %}
</table>

{% endblock %}

library/templates/library/information_form.html
{% extends 'library/base.html' %}
{% block content %}
{% load crispy_forms_tags %}

<div class="profile">
<div >
    
    <a href="{% url 'library:login' %}">&#8592; Back</a>
</div>

<div >
    <h3>Fill in the form and the admins will register you and send the credentials in your email within 24 hours.</h3>
    <form method="POST" action="">
    {%csrf_token%}
    {{form|crispy}}
    <input class="button" type="submit" value="Submit">
    
    </form>
</div>

</div>

{% endblock content %}

library/templates/library/main.html
{% extends 'library/base.html' %} {% block content %}


<div class="row" style="margin: auto; margin-top: 40px;">
  <form method="GET" class="d-flex">
    <input class="form-control me-2" type="text" placeholder="Search" name="search-area" aria-label="Search" value="{{search_input}}">
    <button class="btn btn-outline-success" type="submit">Search</button>
  </form>

{% for book in books %}
<div class="col-md-4" style="margin-top: 50px;">
<div class="card" style="width: 18rem">
  <span style="text-align: center;"></span>
  {% if book.pic %}
  <img src="https://lmsbooks.s3.amazonaws.com{{book.pic.url}}" class="card-img-top" alt="" />
  {% else %}
  <img src="/static/avatar/open-book-clipart-03.png" class="card-img-top" alt="">
  {% endif %}
  <div class="card-body">
    <h5 class="card-title">{{book.title}}</h5>
    <p class="card-text">{{book.summary}}</p>
    <a href="{% url 'library:book' book.id %}" class="btn btn-primary"
      >View Details</a
    >
  </div>
</div>
</div>

{% endfor %}


</div>

{% endblock content %}

library/templates/library/student.html
{% extends 'library/base.html' %}
{% block content %}
<div class="profile">
{% if student.pic %}
<div class="about__img img">
    <img src="https://lmsstudents.s3.amazonaws.com{{student.pic.url}}" alt="">
</div>
{% else %}
<div class="about__img img">
    <img src="/static/avatar/images.png" alt="">
</div>
{% endif %}
<p style="color: white;"><h1 style="color: white;">{{student.name|title}}</h1></p>
<p style="color: white;">Enrollment No: {{student.enrollment_no}}</p>
<p style="color: white;">Date Joined: {{student.date_joined}}</p>
<a  href="{% url 'library:student-update' student.id%}" class="btn btn-primary">Edit Profile</a>
</div>
{% endblock content %}

library/templates/library/student_list.html
{% extends "library/base.html" %} {% block content %}

<div class="container">
  <div class="row" style="margin: auto; margin-top: 40px;">
    <form method="GET" class="d-flex">
      <input class="form-control me-2" type="text" placeholder="Search" name="search-area" aria-label="Search" style="background-color:white ;"
        value="{{search_input}}">
      <button class="btn btn-info" type="submit">Search</button>
    </form>
  </div>
  
<table class="table table-striped table-dark"  style="margin: auto;margin-top: 50px;">
  <thead>
    <tr>
      <th scope="col">SN</th>
      <th scope="col">Student Name</th>
      <th scope="col">Email</th>
      <th scope="col">Status</th>
      <th scope="col">Books</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  {% if students %}
  <tbody>
    {% for student in students %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{student.name}}</td>
      <td>{{student.email}}</td>
      <td>{% if student.is_active %}Active{% else %}Inactive{% endif %}</td>
      <td>{{student.borrowed}}</td>
      <td><a href="{% url 'library:student-update' student.id%}" class="btn btn-primary">Update</a>  <a href="{% url 'library:student-delete' student.id%}" class="btn btn-danger">Delete</a>  <a href="{% url 'library:student-detail' student.id%}" class="btn btn-info">Profile</a> </td>

    </tr>
    {% endfor %}
  </tbody>
  {% else %}
  <tbody><tr><td colspan="6"> No Students.</td></tr></tbody>
  {% endif %}
</table>
{% endblock %}